name: Code Style Checks

on: push

defaults:
  run:
    working-directory: client

jobs:
  style-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        run: yarn
      - name: Check formatting
        run: yarn format:check
      - name: Check linting
        run: yarn lint
